### PR TITLE
feat(safari) support safari for audio recording

### PR DESCRIPTION
**Pull request by lidio601**
I ported a standalone example I had that uses a polyfill + tone.js to record audio as it wasn't working on Safari.

This still doesn't support video recording (on Safari) but you could look into [this](https://github.com/CameraKit/webm-media-recorder).

For now I just duplicated the existing mixin and renamed it to be used by the video-recorder component, and added the code to check if MediaRecorder is defined to disable it (otherwise it will raise an error after the recording starts).

### CODE REVIEW

**Comment by b4dnewz** [comment]
thanks for the very detailed code and PR!

unfortunately I never used safari and I wasn't aware that the plugin wasn't working. I need to download it and test your code

in order to merge this feature the master we could detect the browser using [this code](https://stackoverflow.com/questions/9847580/how-to-detect-safari-chrome-ie-firefox-and-opera-browser/9851769#9851769) and then using an alternative mixin for safari and maybe turn the actual recordermixin in a more generic code that can be used for all browsers and shared with the safari one.

I'll check it as soon as possible and I let you know

**Comment by lidio601** [comment]
Good point.

Should be all done: now it loads the "Safari mixin" only if `MediaRecorder` is missing and I reverted to a single RecorderMixin for clarity.

**Review by b4dnewz — APPROVED** [review]
awesome job! 👍 
since I was rewriting this plugin in order to close issue #2 I'll probably make a few changes to keep it up with [beta branch](https://github.com/codekraft-studio/vue-record/tree/beta) and then merge it all together on master.
probably this evening I've the time to do it, anyway thanks for this PR, very appreciated!

**Comment by lidio601** [comment]
sorry I just realized I had a bug with the audio context, it needs to be started only once.

also I changed the base of my pull request to beta.

**Comment by b4dnewz** [comment]
ok, after thinking a little bit I've decided to change back the base to master and merge it.
initially I thought to merge it into the beta branch since I've updated the mixins in that branch, but to keep the things separate and simple both in code and in project history it's better to merge this new feature you have done into the master and bump the project version.

eventually when I continue working on the beta branch I adapt it to use the new safary mixin.

**Comment by b4dnewz** [comment]
just for the records, your feature is now available in version 0.0.3 commit 886f8018ee861f5443ca62133630cd8a53230ed1

**Pull request merged**
